// Shared Constants for PayPilot

export const PLAN_LIMITS = {
  free_trial: {
    maxInvoicesMonthly: 25,
    maxWhatsAppMonthly: 50,
    maxEmailsMonthly: 100,
    maxCallsMonthly: 0,
    maxAiAnalysesMonthly: 25,
    maxTeamMembers: 2,
    priceInr: 0,
  },
  starter: {
    maxInvoicesMonthly: 100,
    maxWhatsAppMonthly: 250,
    maxEmailsMonthly: 500,
    maxCallsMonthly: 0,
    maxAiAnalysesMonthly: 100,
    maxTeamMembers: 3,
    priceInr: 499,
  },
  growth: {
    maxInvoicesMonthly: 1000,
    maxWhatsAppMonthly: 500,
    maxEmailsMonthly: 1000,
    maxCallsMonthly: 100,
    maxAiAnalysesMonthly: 500,
    maxTeamMembers: 10,
    priceInr: 999,
  },
  pro: {
    maxInvoicesMonthly: 10000,
    maxWhatsAppMonthly: 2000,
    maxEmailsMonthly: 5000,
    maxCallsMonthly: 500,
    maxAiAnalysesMonthly: 2000,
    maxTeamMembers: 25,
    priceInr: 1999,
  },
  enterprise: {
    maxInvoicesMonthly: Infinity,
    maxWhatsAppMonthly: Infinity,
    maxEmailsMonthly: Infinity,
    maxCallsMonthly: Infinity,
    maxAiAnalysesMonthly: Infinity,
    maxTeamMembers: Infinity,
    priceInr: null,
  },
} as const;

export const DEFAULT_FOLLOW_UP_RULES = [
  {
    name: 'Upcoming Due Date Reminder',
    daysRelativeToDue: -3,
    channel: 'email' as const,
    templateSubject: 'Reminder: Invoice {{invoice_number}} is due in 3 days',
    templateBody: 'Hi {{contact_name}}, this is a friendly reminder that invoice {{invoice_number}} for {{amount}} is due on {{due_date}}. You can pay seamlessly using the link below.',
    escalationPriority: 1,
    includePaymentLink: true,
    includeQrCode: true,
  },
  {
    name: 'Due Date Alert',
    daysRelativeToDue: 0,
    channel: 'whatsapp' as const,
    templateSubject: 'Invoice Due Today',
    templateBody: 'Hello {{contact_name}}, your invoice {{invoice_number}} for {{amount}} is due today. Quick pay here: {{payment_link}}',
    escalationPriority: 2,
    includePaymentLink: true,
    includeQrCode: true,
  },
  {
    name: 'First Overdue Notice',
    daysRelativeToDue: 3,
    channel: 'whatsapp' as const,
    templateSubject: 'Overdue Invoice Notice',
    templateBody: 'Hi {{contact_name}}, invoice {{invoice_number}} ({{amount}}) is now 3 days overdue. Please clear the pending dues to avoid account hold.',
    escalationPriority: 3,
    includePaymentLink: true,
    includeQrCode: true,
  },
  {
    name: 'Formal Overdue Notice',
    daysRelativeToDue: 7,
    channel: 'email' as const,
    templateSubject: 'Overdue Notice: Invoice {{invoice_number}} - {{amount}}',
    templateBody: 'Dear {{contact_name}},\n\nOur records indicate invoice {{invoice_number}} for {{amount}} is 7 days past its due date ({{due_date}}). Please settle the outstanding balance immediately.\n\nPayment Link: {{payment_link}}',
    escalationPriority: 4,
    includePaymentLink: true,
    includeQrCode: true,
  },
  {
    name: 'Automated Voice Call Escalation',
    daysRelativeToDue: 14,
    channel: 'call' as const,
    templateSubject: 'Voice Reminder',
    templateBody: 'Hello {{contact_name}}, this is an automated payment reminder from {{company_name}} regarding overdue invoice {{invoice_number}} for {{amount}}. We have sent a quick payment link to your WhatsApp and email.',
    escalationPriority: 5,
    includePaymentLink: true,
    includeQrCode: false,
  },
] as const;