/* Quiet Command Center: dense operational surfaces, restrained mint signals, and purposeful motion. */
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import {
  Activity, AlertCircle, ArrowDownRight, ArrowUpRight, Bell, Bot, Building2, CalendarClock, Check, ChevronDown, ChevronRight, CircleHelp, CreditCard, DollarSign, Download, FileCheck2, FilePlus2, Filter, Gauge, HelpCircle, Inbox, LayoutDashboard, Link2, ListFilter, LogOut, Menu, MessageSquare, MoreHorizontal, PanelLeftClose, PanelLeftOpen, Phone, Plus, Receipt, RefreshCw, Search, Send, Settings, Sparkles, Target, Users, WalletCards, X, Zap
} from "lucide-react";
import { toast } from "sonner";

const navGroups = [
  { label: "Workspace", items: [
    ["Dashboard", LayoutDashboard], ["Customers", Users], ["Invoices", Receipt], ["Payments", CreditCard], ["Payment Links", Link2], ["Follow-ups", RefreshCw], ["Communications", MessageSquare], ["Calls", Phone], ["Analytics", Activity],
  ] },
];
const customers = [
  ["Northstar Labs", "NS", "northstar.io", "$42,850", "$12,400", "Aug 12, 2026", "Today"],
  ["Orbit Systems", "OS", "orbit.systems", "$28,600", "$8,200", "Aug 08, 2026", "Tomorrow"],
  ["Helio Works", "HW", "helio.works", "$18,240", "$0", "Aug 02, 2026", "Aug 19"],
  ["Morrow & Co.", "MC", "morrow.co", "$9,840", "$3,100", "Jul 28, 2026", "Aug 21"],
  ["Pinecone Studio", "PS", "pinecone.studio", "$6,720", "$0", "Jul 22, 2026", "Completed"],
];
const invoices = [
  ["INV-2048", "Northstar Labs", "$12,400", "Aug 14, 2026", "Overdue", "$0", "$12,400", "Today"],
  ["INV-2043", "Orbit Systems", "$8,200", "Aug 18, 2026", "Pending", "$0", "$8,200", "Tomorrow"],
  ["INV-2036", "Helio Works", "$18,240", "Aug 02, 2026", "Paid", "$18,240", "$0", "—"],
  ["INV-2029", "Morrow & Co.", "$6,740", "Jul 28, 2026", "Partially paid", "$3,640", "$3,100", "Aug 21"],
  ["INV-2018", "Pinecone Studio", "$4,500", "Jul 22, 2026", "Paid", "$4,500", "$0", "—"],
];
const activity = [
  ["Payment received", "Helio Works paid INV-2036", "$18,240", "2m ago", "mint"],
  ["Follow-up sent", "WhatsApp reminder to Northstar Labs", "INV-2048", "26m ago", "blue"],
  ["Payment promise", "Orbit Systems promised Aug 18", "$8,200", "1h ago", "amber"],
  ["Invoice created", "INV-2048 for Northstar Labs", "$12,400", "3h ago", "slate"],
];
const chart = [22, 28, 25, 39, 34, 49, 44, 58, 53, 67, 62, 78, 71, 86, 81, 92];

function StatusBadge({ status }: { status: string }) {
  const tone = status.toLowerCase().includes("paid") || status === "Completed" ? "success" : status.toLowerCase().includes("overdue") || status.toLowerCase().includes("failed") ? "danger" : status.toLowerCase().includes("promise") ? "warning" : "neutral";
  return <span className={`status status-${tone}`}><span className="status-dot" />{status}</span>;
}
function StatCard({ label, value, detail, trend, icon: Icon, accent = "mint" }: any) {
  return <div className="stat-card">
    <div className="stat-top"><span className="eyebrow">{label}</span><span className={`icon-box icon-${accent}`}><Icon size={15} /></span></div>
    <div className="stat-value">{value}</div>
    <div className="stat-detail"><span className={trend?.startsWith("+") ? "trend-up" : "trend-flat"}>{trend}</span> {detail}</div>
  </div>;
}
function Sparkline({ values = chart, color = "#9fe870" }: { values?: number[]; color?: string }) {
  const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${100 - v}`).join(" ");
  return <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="sparkline" aria-label="Trend chart"><polyline points={points} fill="none" stroke={color} strokeWidth="2.2" vectorEffect="non-scaling-stroke" /><polyline points={`0,100 ${points} 100,100`} fill={`${color}14`} stroke="none" /></svg>;
}
function SectionHeader({ eyebrow, title, action }: any) { return <div className="section-header"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{action}</div>; }
function EmptyState({ title, text, icon: Icon = Inbox }: any) { return <div className="empty-state"><Icon size={20} /><strong>{title}</strong><span>{text}</span></div>; }
function DataTable({ type }: { type: "invoices" | "customers" | "payments" }) {
  if (type === "customers") return <div className="table-wrap"><table><thead><tr><th>Customer</th><th>Status</th><th>Outstanding</th><th>Overdue</th><th>Last payment</th><th>Next follow-up</th></tr></thead><tbody>{customers.map((c) => <tr key={c[0]}><td><div className="person"><span className="avatar avatar-sm">{c[1]}</span><div><strong>{c[0]}</strong><small>{c[2]}</small></div></div></td><td><StatusBadge status={c[4] === "$0" ? "Healthy" : "Needs attention"} /></td><td className="money">{c[3]}</td><td className={c[4] !== "$0" ? "money danger-text" : "money"}>{c[4]}</td><td>{c[5]}</td><td>{c[6]}</td></tr>)}</tbody></table></div>;
  if (type === "payments") return <div className="table-wrap"><table><thead><tr><th>Payment ID</th><th>Invoice</th><th>Customer</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody>{[["PAY-8942", "INV-2036", "Helio Works", "$18,240", "ACH", "Succeeded", "Aug 15, 2026"], ["PAY-8931", "INV-2029", "Morrow & Co.", "$3,640", "Card", "Succeeded", "Aug 13, 2026"], ["PAY-8910", "INV-2018", "Pinecone Studio", "$4,500", "ACH", "Succeeded", "Aug 10, 2026"], ["PAY-8894", "INV-2007", "Verdant Retail", "$2,180", "Card", "Refunded", "Aug 08, 2026"]].map((p) => <tr key={p[0]}><td className="mono">{p[0]}</td><td className="mono">{p[1]}</td><td>{p[2]}</td><td className="money">{p[3]}</td><td>{p[4]}</td><td><StatusBadge status={p[5]} /></td><td>{p[6]}</td></tr>)}</tbody></table></div>;
  return <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Amount</th><th>Due date</th><th>Status</th><th>Balance</th><th>Next follow-up</th></tr></thead><tbody>{invoices.map((i) => <tr key={i[0]}><td className="mono">{i[0]}</td><td><strong>{i[1]}</strong></td><td className="money">{i[2]}</td><td>{i[3]}</td><td><StatusBadge status={i[4]} /></td><td className={i[6] !== "$0" ? "money danger-text" : "money"}>{i[6]}</td><td>{i[7]}</td></tr>)}</tbody></table></div>;
}
function Dashboard() {
  const [range, setRange] = useState("30 days");
  return <div className="page-stack">
    <div className="welcome-row"><div><p className="eyebrow">Friday, August 15, 2026</p><h1>Good morning, Anika.</h1><p className="muted">Your collection desk is clear enough to focus on what moves cash next.</p></div><div className="button-row"><button className="button secondary" onClick={() => toast.success("Report exported") }><Download size={15}/> Export</button><button className="button primary" onClick={() => toast.success("Invoice composer opened") }><Plus size={15}/> Draft an invoice</button></div></div>
    <div className="stat-grid"><StatCard label="Outstanding" value="$184,620" detail="vs. last month" trend="+8.4%" icon={WalletCards}/><StatCard label="Overdue" value="$42,850" detail="across 8 invoices" trend="+3.2%" icon={AlertCircle} accent="amber"/><StatCard label="Collected this month" value="$96,240" detail="vs. last month" trend="+14.8%" icon={DollarSign}/><StatCard label="Collection rate" value="82.4%" detail="6.1% above target" trend="+6.1%" icon={Target}/></div>
    <div className="dashboard-grid primary-grid">
      <section className="panel chart-panel"><SectionHeader eyebrow="Cash movement" title="Collections over time" action={<div className="segmented">{["7 days", "30 days", "90 days"].map((r) => <button className={range === r ? "selected" : ""} onClick={() => setRange(r)} key={r}>{r}</button>)}</div>}/><div className="chart-legend"><span><i className="legend-dot mint"/>Collected <b>$96.2k</b></span><span><i className="legend-dot slate"/>Outstanding <b>$184.6k</b></span></div><div className="big-chart"><div className="chart-y"><span>$100k</span><span>$75k</span><span>$50k</span><span>$25k</span><span>$0</span></div><div className="chart-stage"><div className="chart-lines"><i/><i/><i/><i/><i/></div><Sparkline/><div className="chart-x"><span>Jul 19</span><span>Jul 26</span><span>Aug 02</span><span>Aug 09</span><span>Aug 15</span></div></div></div></section>
      <section className="panel focus-panel"><SectionHeader eyebrow="Needs attention" title="Overdue exposure" action={<button className="icon-button" aria-label="More options"><MoreHorizontal size={17}/></button>}/><div className="focus-amount">$42,850 <span>across 8 invoices</span></div><div className="progress-bar"><i style={{width:"68%"}}/></div><div className="focus-meta"><span>68% of overdue balance</span><strong>+3.2% this month</strong></div><div className="mini-list">{[["Northstar Labs", "$12,400", "8 days"], ["Morrow & Co.", "$3,100", "4 days"], ["Orbit Systems", "$8,200", "2 days"]].map((x) => <div className="mini-row" key={x[0]}><span className="avatar avatar-xs">{x[0].slice(0,2)}</span><div><strong>{x[0]}</strong><small>{x[2]} overdue</small></div><b>{x[1]}</b></div>)}</div><button className="text-button" onClick={() => toast("Opening overdue invoices")}>Send the next nudge <ChevronRight size={14}/></button></section>
    </div>
    <div className="dashboard-grid secondary-grid"><section className="panel"><SectionHeader eyebrow="Invoice activity" title="Invoices needing motion" action={<button className="text-button" onClick={() => toast("Invoices view selected")}>Open ledger <ChevronRight size={14}/></button>}/><DataTable type="invoices"/></section><section className="panel activity-panel"><SectionHeader eyebrow="Live feed" title="Collection pulse" action={<button className="icon-button"><MoreHorizontal size={17}/></button>}/><div className="activity-list">{activity.map((a) => <div className="activity-row" key={a[1]}><span className={`activity-icon ${a[4]}`}><Check size={13}/></span><div><strong>{a[0]}</strong><p>{a[1]}</p></div><div className="activity-right"><b>{a[2]}</b><small>{a[3]}</small></div></div>)}</div></section></div>
  </div>;
}
function GenericPage({ page }: { page: string }) {
  const [query, setQuery] = useState("");
  const config: any = { Customers: { icon: Users, eyebrow: "Relationship ledger", title: "Customers", desc: "Know who owes you, what they owe, and what happens next.", action: "Add customer", table: "customers" }, Invoices: { icon: Receipt, eyebrow: "Accounts receivable", title: "Invoices", desc: "A clear view of every invoice from issue to collection.", action: "Create invoice", table: "invoices" }, Payments: { icon: CreditCard, eyebrow: "Cash movement", title: "Payments", desc: "Track successful, pending, failed, and refunded payments.", action: "Record payment", table: "payments" }, "Payment Links": { icon: Link2, eyebrow: "Frictionless collection", title: "Payment links", desc: "Give customers a direct route from reminder to paid.", action: "Create payment link" }, "Follow-ups": { icon: RefreshCw, eyebrow: "Collection system", title: "Follow-ups", desc: "Turn overdue invoices into a consistent, measurable workflow.", action: "Create rule" }, Communications: { icon: MessageSquare, eyebrow: "Unified inbox", title: "Communications", desc: "Every customer conversation, with its financial context attached.", action: "New message" }, Calls: { icon: Phone, eyebrow: "Conversation intelligence", title: "Calls", desc: "Review scheduled calls, outcomes, and payment promises.", action: "Schedule call" }, Analytics: { icon: Activity, eyebrow: "Performance", title: "Analytics", desc: "See the signals behind your collection rate.", action: "Export report" }, Billing: { icon: CreditCard, eyebrow: "Workspace plan", title: "Billing", desc: "Your plan, usage, and billing history in one place.", action: "Change plan" }, Settings: { icon: Settings, eyebrow: "Workspace controls", title: "Settings", desc: "Tune PayPilot to how your team collects revenue.", action: "Save changes" } };
  const c = config[page] || config.Customers; const Icon = c.icon;
  return <div className="page-stack"><div className="page-heading"><div className="heading-icon"><Icon size={18}/></div><div><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="muted">{c.desc}</p></div><button className="button primary page-action" onClick={() => toast.success(`${c.action} ready`)}><Plus size={15}/>{c.action}</button></div>{(page === "Customers" || page === "Invoices" || page === "Payments") ? <><div className="subnav"><button className="active">All</button><button>Needs attention</button><button>Recently updated</button><div className="subnav-spacer"/><div className="search-inline"><Search size={14}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${page.toLowerCase()}...`}/></div><button className="button secondary"><Filter size={14}/> Filters</button></div><div className="metric-strip"><span><b>{page === "Payments" ? "$126,460" : page === "Invoices" ? "48" : "126"}</b><small>{page === "Payments" ? "Total collected" : page === "Invoices" ? "Total invoices" : "Active customers"}</small></span><span><b>{page === "Payments" ? "$4,280" : page === "Invoices" ? "$42,850" : "$184,620"}</b><small>{page === "Payments" ? "Pending" : page === "Invoices" ? "Overdue" : "Outstanding"}</small></span><span><b>{page === "Payments" ? "98.2%" : page === "Invoices" ? "82.4%" : "91.6%"}</b><small>Health score</small></span></div><section className="panel"><DataTable type={c.table}/></section></> : <RoutePlaceholder page={page} action={c.action}/>}</div>;
}
function RoutePlaceholder({ page, action }: { page: string; action: string }) { const isFollow = page === "Follow-ups"; return <div className="dashboard-grid secondary-grid"><section className="panel"><SectionHeader eyebrow={isFollow ? "Automation map" : "Workspace overview"} title={isFollow ? "A calmer way to collect" : `${page} at a glance`} action={<button className="button primary" onClick={() => toast.success(`${action} ready`)}><Plus size={14}/>{action}</button>}/>{isFollow ? <div className="flow"><div className="flow-node trigger"><span className="flow-kicker">Trigger</span><strong>Invoice becomes overdue</strong></div><ChevronDown/><div className="flow-node"><span className="flow-kicker">Wait 1 day</span><strong>Send WhatsApp reminder</strong></div><ChevronDown/><div className="flow-node"><span className="flow-kicker">Wait 3 days</span><strong>Send email reminder</strong></div><ChevronDown/><div className="flow-node"><span className="flow-kicker">Wait 7 days</span><strong>Place a call</strong></div></div> : <EmptyState icon={Sparkles} title={`Your ${page.toLowerCase()} workspace is ready`} text="Mock data and reusable surfaces are in place. Connect the real workflow when you are ready."/>}</section><section className="panel"><SectionHeader eyebrow="At a glance" title="This period" action={<button className="icon-button"><MoreHorizontal size={17}/></button>}/><div className="placeholder-stats"><div><span className="eyebrow">Completed</span><strong>{page === "Calls" ? "38" : page === "Analytics" ? "82.4%" : "24"}</strong><small className="trend-up">+12.6%</small></div><div><span className="eyebrow">Pending</span><strong>{page === "Calls" ? "7" : "16"}</strong><small>requires review</small></div><div><span className="eyebrow">Failed</span><strong>{page === "Calls" ? "2" : "3"}</strong><small className="danger-text">needs attention</small></div></div></section></div>; }

function Sidebar({ active, setActive, collapsed, setCollapsed, mobileOpen, setMobileOpen }: any) { return <aside className={`sidebar ${collapsed ? "collapsed" : ""} ${mobileOpen ? "mobile-open" : ""}`}><div className="brand"><img src="/manus-storage/paypilot-mark_6d933dcf.png" alt="PayPilot mark"/><span>PayPilot</span><button className="collapse-button" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <PanelLeftOpen size={16}/> : <PanelLeftClose size={16}/>}</button></div><div className="org-switch"><span className="org-logo">AC</span><span className="org-copy"><b>Acme Corporation</b><small>Growth plan</small></span><ChevronDown size={14}/></div><nav>{navGroups[0].items.map(([label, Icon]: any) => <button key={String(label)} className={active === label ? "nav-item active" : "nav-item"} onClick={() => {setActive(label); setMobileOpen(false)}}><Icon size={17}/><span>{label}</span>{label === "Follow-ups" && <em>8</em>}</button>)}<div className="nav-rule"/><button className={active === "Settings" ? "nav-item active" : "nav-item"} onClick={() => {setActive("Settings"); setMobileOpen(false)}}><Settings size={17}/><span>Settings</span></button></nav><div className="sidebar-bottom"><div className="sidebar-help"><CircleHelp size={15}/><span>Help center</span><kbd>?</kbd></div><div className="user-row"><span className="avatar">AK</span><span className="user-copy"><b>Anika Kapoor</b><small>Owner · Pro plan</small></span><button className="icon-button"><MoreHorizontal size={16}/></button></div></div></aside>; }
function TopBar({ active, onMenu, onSearch }: any) { return <header className="topbar"><div className="mobile-menu"><button className="icon-button" onClick={onMenu}><Menu size={18}/></button></div><div className="top-title"><span>{active}</span><ChevronRight size={13}/><b>Overview</b></div><div className="top-actions"><button className="global-search" onClick={onSearch}><Search size={15}/><span>Search anything...</span><kbd>⌘ K</kbd></button><button className="icon-button"><Bell size={17}/><i className="notification-dot"/></button><button className="icon-button"><CircleHelp size={17}/></button><span className="avatar avatar-top">AK</span></div></header>; }
function CommandMenu({ open, close, setActive }: any) { const [q, setQ] = useState(""); const commands = [["Create invoice", FilePlus2, "Invoices"], ["Add customer", Users, "Customers"], ["Create payment link", Link2, "Payment Links"], ["Create follow-up", Zap, "Follow-ups"], ["Search invoices", Search, "Invoices"], ["Open settings", Settings, "Settings"]]; if (!open) return null; return <div className="modal-backdrop" onClick={close}><div className="command-menu" onClick={e => e.stopPropagation()}><div className="command-search"><Search size={18}/><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Type a command or search..."/><kbd>ESC</kbd></div><div className="command-label">Suggestions</div>{commands.filter(c => String(c[0]).toLowerCase().includes(q.toLowerCase())).map(([label, Icon, page]: any) => <button className="command-item" key={label} onClick={() => {setActive(page); close(); toast.success(`${label} opened`);}}><span><Icon size={16}/></span><b>{label}</b><ChevronRight size={14}/></button>)}<div className="command-footer"><span>Navigate <kbd>↑↓</kbd></span><span>Open <kbd>↵</kbd></span><span>Close <kbd>ESC</kbd></span></div></div></div>; }
export default function Home() { const [active, setActive] = useState("Dashboard"); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [command, setCommand] = useState(false); useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setCommand(true); } if (e.key === "Escape") setCommand(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []); const content = useMemo(() => active === "Dashboard" ? <Dashboard/> : <GenericPage page={active}/>, [active]); return <div className="app-shell"><Sidebar {...{active, setActive, collapsed, setCollapsed, mobileOpen, setMobileOpen}}/><div className="main-shell"><TopBar active={active} onMenu={() => setMobileOpen(true)} onSearch={() => setCommand(true)}/><main className="workspace">{content}</main></div><CommandMenu open={command} close={() => setCommand(false)} setActive={setActive}/>{mobileOpen && <div className="mobile-scrim" onClick={() => setMobileOpen(false)}/>}</div>; }
